name: ton_gpt
description: A flutter app template.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  intl:

dev_dependencies:
  auto_route_generator:
  bloc_test: ^9.1.1
  build_runner:

  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
